### PR TITLE
fix: quickfix for react-lottie dependency

### PR DESCRIPTION
**Pull request by theborakompanioni**
Quickfix for react-lottie dependency issue. 
react-lottie is outdated and seems not to be maintained anymore.

This will include the [plain react-lottie source]( https://github.com/chenqingspring/react-lottie/blob/56f72845de2ed652f763b92978a06201d3333dd8/src/index.js) with one minor adaption:
- replace `componentWillUpdate` with `UNSAFE_componentWillUpdate`.

After this `npm update` and `npm  run build` should work fine again.

### CODE REVIEW

**Comment by dnlggr** [comment]
> react-lottie is outdated and seems not to be maintained anymore.

Omg really? Thanks for nothing Airbnb...

**Comment by theborakompanioni** [comment]
> > react-lottie is outdated and seems not to be maintained anymore.
> 
> Omg really? Thanks for nothing Airbnb...

Not maintained by Airbnb : )
[`lottie-web`](https://github.com/airbnb/lottie-web) seems to be maintained _very well_ (changelog, no breaking changes, etc.)

**Comment by dnlggr** [comment]
Ah I see, `react-lottie` is just a wrapper. 👍 Makes sense.

**Review by dergigi — APPROVED** [review]
LGTM, thx for the quick fix. Let's clean this up next week or something.

**Pull request merged**
