### PR TITLE
fix: thumbnail generation

### PR DESCRIPTION
**Pull request by cnix123**
Moves the thumbnail generation out from the Next.js build into a separate "pre-build" step. Now it's basically just a bash script calling Imagemagick to generate the thumbnails.

This should fix the memory issues we had on the CI and has the additional benefit that we don't have to use the [problematic](https://github.com/seetee-io/seetee-io/pull/73) squoosh library anymore which somehow (I don't know how) seemed to cause the [memory issues](https://app.netlify.com/teams/seetee-hqg5ruu/builds/62fa6adf88898c000af713a6) on CI and also forced us to [pin a specific node version](https://github.com/seetee-io/seetee-io/pull/73).

This flow is still not ideal because the thumbnails still don't get commited to Git. That means they'll be re-generated each time. Unfortunately, there's no straight forward way to fix this I believe. It sounds super easy, but our deploy process makes it quite complicated. Let's talk about how to best do this some other time.

For now this is a fix to the failing builds and means that at least we don't need to manually generate the thumbnails anymore. Let me know what you think.

### CODE REVIEW

**Review by theborakompanioni — DISMISSED** [review]
tACK.

`@squoosh/lib` is still present in `package-lock.json` which creates diffs after `npm install`, can you also commit those changes?
Question: Albeit increased file size, the new thumbnails have better quality - do you think the other thumbnails should be regenerated?

**Review by dergigi — APPROVED** [review]
Pushed the `npm i` changes. Will merge this now, let's see if it works. Might re-generate the thumbs in a separate PR.

**Comment by dergigi** [comment]
Re-generated all thumbs in #78

**Comment by cnix123** [comment]
> Albeit increased file size, the new thumbnails have better quality

We can also play around with the compression settings. I just used something that looked ok and seemed to produce images under 100KB (if I remember correctly).

**Pull request merged**
